# Generated by Django 3.0.7 on 2023-05-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230524_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
