# Generated by Django 3.0.7 on 2023-06-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20230619_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
