# Generated by Django 3.0.7 on 2023-06-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_saleitem_tracking_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salebilldetails',
            old_name='tracking_code',
            new_name='codigo_seguimiento',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='tracking_code',
            new_name='codigo_seguimiento',
        ),
    ]
