# Generated by Django 3.0.7 on 2023-07-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20230619_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='codigo_seguimiento',
            field=models.CharField(max_length=20),
        ),
    ]
