# Generated by Django 3.0.7 on 2023-07-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20230711_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
