# Generated by Django 3.0.7 on 2023-07-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20230711_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
